<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LXMedical Admin_h-8 w-8 rounded-full</name>
   <tag></tag>
   <elementGuidId>f72a62bd-6423-4604-aca9-4b2fb18e41aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-8.w-8.rounded-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-menu-button-1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ee031e2-d9c1-454a-8b21-fa8bb6d985a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/dummy-profile-image.6a38ae8c.png</value>
      <webElementGuid>727da932-bd66-482f-aa14-1c2e8dce9fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>pankod</value>
      <webElementGuid>d8c9cdf2-a342-43a9-be31-95f83b84cc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>4f3475c6-ea05-4398-b9f6-29ca0eb9b4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>b9fed556-e81c-4da2-88ed-0cc99d41ec1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-8 w-8 rounded-full</value>
      <webElementGuid>69fa514b-0fb7-4f10-900d-9c58ad01ddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-button-1&quot;)/img[@class=&quot;h-8 w-8 rounded-full&quot;]</value>
      <webElementGuid>0bb020b2-b9a7-47f3-b838-3a6a95dda9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-menu-button-1']/img</value>
      <webElementGuid>041131b5-b38a-4f27-b534-6ccd151e5549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='pankod']</value>
      <webElementGuid>b6bb3653-35d9-4ea6-bb66-3f062b19b750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>8e36da42-5703-45fe-a30d-f7f4fec545bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/dummy-profile-image.6a38ae8c.png' and @alt = 'pankod']</value>
      <webElementGuid>fdff462f-9ce2-4ee4-a746-29a7cb8d6616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
